[project]
name = "travel-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aiurfb6_amway", email = "Harsh.Bhagwani@amway.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
travel-assistant = "travel_assistant:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
